'use client'
import {useEffect,useMemo,useState} from 'react'
import {getSupabaseBrowserClient} from '../lib/supabase'
const money=n=>`$${Number(n||0).toLocaleString('es-MX',{minimumFractionDigits:2})}`
const labels={pending:'Pendiente',accepted:'Aceptado',preparing:'Preparando',ready:'Listo',assigned:'Asignado',picked_up:'Recogido',on_the_way:'En camino',delivered:'Entregado',cancelled:'Cancelado'}
export default function Page(){
 const supabase=useMemo(()=>getSupabaseBrowserClient(),[]);const [session,setSession]=useState(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[tab,setTab]=useState('home'),[orders,setOrders]=useState([]),[fin,setFin]=useState([]),[merchants,setMerchants]=useState([]),[couriers,setCouriers]=useState([]),[selected,setSelected]=useState(null),[msg,setMsg]=useState('')
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)load()});const {data:s}=supabase.auth.onAuthStateChange((_e,x)=>{setSession(x);if(x)load()});const ch=supabase.channel('admin-live').on('postgres_changes',{event:'*',schema:'public',table:'orders'},load).subscribe();return()=>{s.subscription.unsubscribe();supabase.removeChannel(ch)}},[])
 async function login(e){e.preventDefault();const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setMsg(error.message)}
 async function load(){const [o,f,m,c]=await Promise.all([supabase.from('orders').select('*,merchants(name)').order('created_at',{ascending:false}).limit(250),supabase.from('order_financials').select('*').order('created_at',{ascending:false}).limit(250),supabase.from('merchants').select('*').order('name'),supabase.from('courier_profiles').select('*')]);if(o.error)return setMsg(o.error.message);setOrders(o.data||[]);setFin(f.data||[]);setMerchants(m.data||[]);setCouriers(c.data||[])}
 async function setStatus(o,status){const {error}=await supabase.from('orders').update({status,...(status==='delivered'?{delivered_at:new Date().toISOString()}:{})}).eq('id',o.id);if(error)return setMsg(error.message);setSelected(null);load()}
 async function assign(o,id){const {error}=await supabase.from('orders').update({courier_id:id||null,delivery_mode:'guti',status:id?'assigned':'ready'}).eq('id',o.id);if(error)return setMsg(error.message);setSelected(null);load()}
 const sum=k=>fin.reduce((a,x)=>a+Number(x[k]||0),0),active=orders.filter(o=>!['delivered','cancelled'].includes(o.status))
 if(!session)return <main className="login"><form onSubmit={login}><div className="logo">Guti<span>.mx</span></div><small>PANEL ADMIN</small><h1>Centro de operación</h1><p>Gutiérrez Zamora</p><input type="email" placeholder="Correo" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Contraseña" value={password} onChange={e=>setPassword(e.target.value)}/><button>Entrar</button>{msg&&<em>{msg}</em>}</form></main>
 return <div className="layout"><aside><div className="logo">Guti<span>.mx</span></div><i>● Operación en vivo</i>{[['home','Resumen'],['orders','Pedidos'],['money','Finanzas'],['merchants','Negocios'],['couriers','Repartidores']].map(([a,b])=><button key={a} className={tab===a?'on':''} onClick={()=>setTab(a)}>{b}</button>)}<button onClick={()=>supabase.auth.signOut()}>Salir</button></aside><main><header><div><small>GUTIÉRREZ ZAMORA</small><h1>{{home:'Centro de operación',orders:'Pedidos',money:'Finanzas',merchants:'Negocios',couriers:'Repartidores'}[tab]}</h1></div><button onClick={load}>↻ Actualizar</button></header>{msg&&<div className="alert">{msg}</div>}
 {tab==='home'&&<><section className="kpis"><article><small>Venta procesada</small><b>{money(sum('customer_total'))}</b></article><article><small>Ingreso Guti</small><b>{money(sum('guti_revenue'))}</b></article><article><small>Neto negocios</small><b>{money(sum('merchant_net'))}</b></article><article><small>Reparto</small><b>{money(sum('courier_payable'))}</b></article></section><section className="panel"><div className="head"><h2>Pedidos activos</h2><span>{active.length}</span></div>{active.map(o=><button className="feed" key={o.id} onClick={()=>setSelected(o)}><div><b>{o.merchants?.name}</b><small>#{o.id.slice(0,7)}</small></div><mark>{labels[o.status]||o.status}</mark><strong>{money(o.total)}</strong></button>)}</section></>}
 {tab==='orders'&&<section className="panel table"><table><thead><tr><th>Pedido</th><th>Negocio</th><th>Pago</th><th>Total</th><th>Estado</th><th/></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>#{o.id.slice(0,7)}</td><td>{o.merchants?.name}</td><td>{o.payment_method}<small>{o.payment_status}</small></td><td>{money(o.total)}</td><td><mark>{labels[o.status]}</mark></td><td><button onClick={()=>setSelected(o)}>Gestionar</button></td></tr>)}</tbody></table></section>}
 {tab==='money'&&<><section className="kpis"><article><small>GMV</small><b>{money(sum('customer_total'))}</b></article><article><small>Comisión</small><b>{money(sum('commission_amount'))}</b></article><article><small>Negocios</small><b>{money(sum('merchant_net'))}</b></article><article><small>Repartidores</small><b>{money(sum('courier_payable'))}</b></article></section><section className="panel table"><table><thead><tr><th>Pedido</th><th>Subtotal</th><th>Envío</th><th>Comisión</th><th>Negocio</th><th>Repartidor</th><th>Guti</th></tr></thead><tbody>{fin.map(f=><tr key={f.order_id}><td>#{f.order_id.slice(0,7)}</td><td>{money(f.subtotal)}</td><td>{money(f.delivery_fee)}</td><td>{money(f.commission_amount)}</td><td>{money(f.merchant_net)}</td><td>{money(f.courier_payable)}</td><td><b>{money(f.guti_revenue)}</b></td></tr>)}</tbody></table></section></>}
 {tab==='merchants'&&<section className="cards">{merchants.map(m=><article key={m.id}><div>{m.name?.[0]}</div><b>{m.name}</b><small>{m.is_open?'Abierto':'Cerrado'} · {m.is_active?'Activo':'Inactivo'}</small></article>)}</section>}
 {tab==='couriers'&&<section className="cards">{couriers.map(c=><article key={c.user_id}><div>R</div><b>Repartidor</b><small>{c.user_id.slice(0,8)}</small></article>)}</section>}
 </main>{selected&&<div className="back" onClick={()=>setSelected(null)}><section className="modal" onClick={e=>e.stopPropagation()}><button className="x" onClick={()=>setSelected(null)}>×</button><small>PEDIDO #{selected.id.slice(0,8)}</small><h2>{selected.merchants?.name}</h2><h3>{money(selected.total)}</h3><label>Repartidor<select value={selected.courier_id||''} onChange={e=>assign(selected,e.target.value)}><option value="">Sin asignar</option>{couriers.map(c=><option key={c.user_id} value={c.user_id}>{c.user_id.slice(0,8)}</option>)}</select></label><div className="actions"><button onClick={()=>setStatus(selected,'cancelled')}>Cancelar</button><button onClick={()=>setStatus(selected,'delivered')}>Marcar entregado</button></div></section></div>}</div>
}